<?php declare(strict_types=1); 

namespace App\Enums\WebhookEnums;

enum WebhookAsaas: string
{
  CASE PAYMENT_CREATED = 'PAYMENT_CREATED';
  CASE PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED';
  CASE PAYMENT_RECEIVED = 'PAYMENT_RECEIVED';
  CASE PAYMENT_OVERDUE = 'PAYMENT_OVERDUE';
  CASE PAYMENT_REFUNDED = 'PAYMENT_REFUNDED';
}